
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_RESERVATIONS_PENDING = 'REQUEST_RESERVATIONS_PENDING'
export const REQUEST_RESERVATIONS_SUCCESS = 'REQUEST_RESERVATIONS_SUCCESS'
export const REQUEST_RESERVATIONS_FAILED = 'REQUEST_RESERVATIONS_FAILED'